### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MHageH** [mzahana/MavLinkBridge#1]
Hello, could you explain more about the functionality of this bridge?

**Comment by mzahana** [comment]
I use this as a mavlink bridge between a flight controller (Pixhawk), and a ground control station, my PC/laptop. This bridge is compiled on a companion computer (ODroid) which is connected to Pixhawk via USB/FTDI cable.

1- the odroid speaks to the Pixhawk via serial connection
2- the odroid speaks to the laptop via WiFi

Pixhawk <--> Odroid<--> laptop.

I will elaborate on how it is used later on.

**Comment by MHageH** [comment]
Well understood, thanks
